// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./components/Chat.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FormButton: typeof import('./components/FormButton.vue')['default']
    FormInput: typeof import('./components/FormInput.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    OpenedChat: typeof import('./components/OpenedChat.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
